version: '3.8'

services:
  api:
    build: .
    ports:
      - '3000:3000'
    environment:
      - MONGO_URI=mongodb://mongo:27017/livesync
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongo
      - redis
    networks:
      - livesync-net

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    networks:
      - livesync-net

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    networks:
      - livesync-net
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
      - automerge 
    networks:
      - livesync-net

  automerge:
    build:
      context: .
      dockerfile: Dockerfile.automerge
    working_dir: /app
    command: node src/socket.js
    ports:
      - '1234:1234'
    depends_on:
      - mongo
      - redis
    env_file:
      - .env
    networks:
      - livesync-net

networks:
  livesync-net:
    driver: bridge
