name: CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        env:
          NODE_ENV: test
          JWT_SECRET: testsecret
        run: npm test

  build-and-push:
    name: Build and push images to GHCR
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Derive lower-case owner for GHCR
        shell: bash
        run: echo "GHCR_OWNER=${GITHUB_REPOSITORY_OWNER,,}" >> "$GITHUB_ENV"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata (API)
        id: meta_api
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ env.GHCR_OWNER }}/livesync-backend-api
          tags: |
            type=raw,value=latest
            type=sha

      - name: Build and push API image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta_api.outputs.tags }}
          labels: ${{ steps.meta_api.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Extract Docker metadata (Automerge WS)
        id: meta_ws
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ env.GHCR_OWNER }}/livesync-backend-automerge
          tags: |
            type=raw,value=latest
            type=sha

      - name: Build and push Automerge WS image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.automerge
          push: true
          tags: ${{ steps.meta_ws.outputs.tags }}
          labels: ${{ steps.meta_ws.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy-railway:
    name: Trigger Railway deploy
    runs-on: ubuntu-latest
    needs: build-and-push
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Trigger Railway Deploy Hook
        env:
          RAILWAY_DEPLOY_HOOK: ${{ secrets.RAILWAY_DEPLOY_HOOK }}
        run: |
          if [ -z "$RAILWAY_DEPLOY_HOOK" ]; then
            echo "RAILWAY_DEPLOY_HOOK not set; skipping deploy trigger.";
            exit 0;
          fi
          curl -fsS -X POST "$RAILWAY_DEPLOY_HOOK"


